#!/usr/bin/env python

import requests
from selectolax.parser import HTMLParser
from unidecode import unidecode
import pandas as pd
import typer



class OwghatBase:
    def __init__(self):
        self.dict_data : dict = dict()
    
    def print_as_table(self):
        import tableprint as tp
        headers = list(self.dict_data.keys())
        oogat_times = list(self.dict_data.values())
        tp.table([oogat_times], headers)
        
    def print_as_dict(self):
        # from pprint import pprint
        from rich import print as pprint
        pprint(self.dict_data)
        

class Owghat_time_ir(OwghatBase):
    url = "https://time.ir"
    
    def __init__(self):
        super().__init__()
        self.get_data()
    
    def get_data(self):
        content = requests.get(self.url)
        tree = HTMLParser(content.text)
        
        oogat_span_root = "#ctl00_cphTop_Sampa_Web_View_EphemerisUI_EphemerisByCity12cphTop_3736_lbl"
        all_oogat = dict()
        for oogat_str in ["AzanMorning", "AzanSunrise", "AzanNoon", "AzanSunset", "AzanNight", "MidNight"]:
            oogat_id = oogat_span_root + oogat_str
            oogat_time = unidecode(tree.css(oogat_id)[0].text())
            all_oogat[oogat_str] = oogat_time
        self.dict_data = all_oogat
        return all_oogat
    

        


valid_names = ["dict", "table"]
def complete_name(incomplete: str):
    completion = []
    for name in valid_names:
        if name.startswith(incomplete.lower()):
            completion.append(name)
    return completion
    
    


def main(show_as : str = typer.Option(
        "table", help="Choose the way of display output [dict, table]", autocompletion=complete_name)
        ):
    owghat = Owghat_time_ir()
    if show_as == "dict" :
        owghat.print_as_dict()
    if show_as == "table":
        owghat.print_as_table()


if __name__ == "__main__":
    typer.run(main)