#!/usr/bin/env python

import requests
from selectolax.parser import HTMLParser
from unidecode import unidecode
import pandas as pd
import time
import typer
from typing import Dict, List
from rich import print as rprint




class OwghatBase:
    def __init__(self):
        self.dict_data : Dict[str, str] = dict()
        self.headers : List[str]=  ["Morning Azan", "Sunrise", "Noon Azan", 
                                    "Sunset", "Night Azan", "Mid-night"]
    
    def print_as_table(self):
        import tableprint as tp
        headers = list(self.dict_data.keys())
        oogat_times = list(self.dict_data.values())
        tp.table([oogat_times], headers)
        
        
    def print_as_dict(self):
        # from pprint import pprint
        rprint(self.dict_data)
        
    def print_as_complete(self):
        from rich_tools import df_to_table
        from rich.table import Table
        dt = self.get_date()
        t = time.strftime("%H:%M:%S")
        table = Table(title="Salah Times - {} {}".format(dt, t))
        df = pd.DataFrame([self.dict_data])
        table = df_to_table(df, table, show_index=False)
        rprint(table)
        
        

class Owghat_time_ir(OwghatBase):
    url = "https://time.ir"
    
    def __init__(self):
        super().__init__()
        self._get_tree()
        self.get_data()
        
    def _get_tree(self):
        content = requests.get(self.url)
        self.tree = HTMLParser(content.text)
    
    def get_data(self):        
        oogat_span_root = "#ctl00_cphTop_Sampa_Web_View_EphemerisUI_EphemerisByCity12cphTop_3736_lbl"
        oogat_map = zip(["AzanMorning", "AzanSunrise", "AzanNoon", 
                              "AzanSunset", "AzanNight", "MidNight"], self.headers)
        
        all_oogat = dict()
        for oogat_str, oogat_key in oogat_map:
            oogat_id = oogat_span_root + oogat_str
            oogat_time = unidecode(self.tree.css(oogat_id)[0].text())
            all_oogat[oogat_key] = oogat_time
        self.dict_data = all_oogat
        return all_oogat
    
    def get_date(self):
        shamsi_id = "#ctl00_cphTop_Sampa_Web_View_TimeUI_ShowDate00cphTop_3734_lblShamsiNumeral"
        return unidecode(self.tree.css(shamsi_id)[0].text())
    
    
        

        


valid_names = ["dict", "table", "complete"]
def complete_name(incomplete: str):
    completion = []
    for name in valid_names:
        if name.startswith(incomplete.lower()):
            completion.append(name)
    return completion
    
    


def main(show_as : str = typer.Option(
        "complete", help="Choose the way of display output [dict, complete, table]", autocompletion=complete_name)
        ):
    owghat = Owghat_time_ir()
    if show_as == "dict" :
        owghat.print_as_dict()
    if show_as == "table":
        owghat.print_as_table()
    if show_as == "complete":
        owghat.print_as_complete()


if __name__ == "__main__":
    typer.run(main)